- alias: Turn off all lights when out
  description: ''
  trigger:
    - platform: state
      entity_id: binary_sensor.door_lock_away_mode_enabled
      to: "on"
  condition: []
  action:
    - service: script.all_lights_off
      data: {}
  mode: single
- alias: Turn on lights when come home
  description: ''
  trigger:
    - platform: state
      entity_id: binary_sensor.door_lock_away_mode_enabled
      from: "on"
      to: "off"
  condition: []
  action:
    - service: light.turn_on
      target:
        entity_id:
        - light.toilet
        - light.bathroom
  mode: single
