# automations for light in toilet when check motions
- alias: Turn the light in toilet on/off when motion
  description: 'Turn off when no motion more than "X" and open toilet door more than "Y"'
  trigger:
    - platform: state
      entity_id: binary_sensor.corridor_motion_registered
      to: "on"
      id: motion_detected
    - platform: state
      entity_id: binary_sensor.corridor_motion_sensor_motion
      from: "on"
      to: "off"
      for: !secret no_motion_in_corridor_time
      id: no_motion
  action:
    - choose:
      - conditions:
        - condition: and
          conditions:
            - condition: trigger
              id: motion_detected
            - condition: state
              entity_id: light.toilet
              state: "off"
        sequence:
          - service: light.turn_on
            target:
              entity_id: light.toilet
      - conditions:
        - condition: trigger
          id: no_motion
        - condition: state
          entity_id: binary_sensor.toilet_contact_sensor_door
          state: "on"
          for: !secret toilet_door_open_time
        sequence:
          - service: light.turn_off
            target:
              entity_id: light.toilet
      default: []
  mode: single

